import React, { FC, ReactNode } from "react";
import { useSession } from "next-auth/react";
import SideMenu from "@/components/SideMenu";
import scss from "./Layout.module.scss";
import Head from "next/head";

interface ILatoutProps {
  children?: ReactNode;
}

const Layout: FC<ILatoutProps> = ({ children }) => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>DataSoft - Data Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={scss.layout}
        style={{ padding: session ? "0 24px 0 80px" : 0 }}
      >
        {session && <SideMenu />}
        {children}
      </main>
    </>
  );
};

export default Layout;
